name: Trigger nightly build

on:
  push:

jobs:

  notify-nightly:
    name: "Trigger new build on nightly-deauther"
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        run: |
          curl -X POST https://api.github.com/repos/spacehuhntech/nightly-deauther/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "Deauther V3 ${{ github.sha::8 }}", "client_payload": {}}'
